### ISSUE TITLE
Bug:  GET https://www.instaclone.net/api/user/shegusi/posts/12 404 (Not Found)

### ISSUE THREAD

**Issue by chawaa** [Sandermoen/instaclone#12]
The profile page could not display more than 12 posts. When scrolling down to browse more posts, an error page appears.

![image](https://user-images.githubusercontent.com/59247295/107882511-a78f3300-6e9e-11eb-9395-240b0e9cbff0.png)

![bug](https://user-images.githubusercontent.com/59247295/113080786-0bc94480-920a-11eb-86df-fcd8d1e164b8.gif)

**Comment by Orca-web** [comment]
Generate some duplicate posts
![image](https://user-images.githubusercontent.com/59247295/109808284-df99c280-7c61-11eb-9caf-ea9107fcff45.png)
