### ISSUE TITLE
I am getting an “Invalid Host header” message, when running instaclone app on  www.niuozbi.com

### ISSUE THREAD

**Issue by Joanne02** [Sandermoen/instaclone#5]
> [**Installation problem**](https://github.com/Sandermoen/instaclone/issues/3)
> There is “Invalid Host Header” error?
> the problem may be related to some firewall settings for your server?

I checked the firewall. It's not its problem.

However  what I've gathered from stackoverflow, it seems that the problem may be related to webpack-dev-server  adds a host check.  （[refer link](https://stackoverflow.com/questions/43619644/i-am-getting-an-invalid-host-header-message-when-running-my-react-app-in-a-we)）.

---

How did you configure the sample website to remove port 3000？

**Comment by Sandermoen** [comment]
I should probably mention that if you intend to run the website in a production environment you do not use the webpack dev server. You have to build the static files and serve them using a webserver. The backend is already configured to serve the static files, all you have to do is run __npm run build__ and start the backend with __npm start__ making sure that the __NODE_ENV__ is in __production__.

**Comment by Joanne02** [comment]
@Sandermoen thank you！
