### ISSUE TITLE
Miss designs

### ISSUE THREAD

**Issue by zakariaelharrak** [Sandermoen/instaclone#62]
I have navigated some clones and noticed that some of them do not exactly match the original website and as named clones mean copying the original website and pasting it.
example : 
![image](https://github.com/Sandermoen/instaclone/assets/58367411/8a27679c-0b14-441d-b9b2-8838791d4653)
![image](https://github.com/Sandermoen/instaclone/assets/58367411/e91d81c3-0572-447e-950e-2318b89f4b4d)

**Comment by Sandermoen** [comment]
If you did one google search you'd realize Instagram used to look like this
a year ago. Websites change.
